Repository inviqa/harness-base-php, pull requests merged in 2022-01, with the labels that each got.

#656 Add horizontal pod autoscaler and pod disruption budgets
  src/_base/helm/app/templates/horizontal-pod-autoscaler.yaml
  src/_base/helm/app/templates/pod-disruption-budgets.yaml
Labels: enhancement, harness-all

#657 Fix formatting of pdb and hpa templates
  src/_base/helm/app/templates/horizontal-pod-autoscaler.yaml
  src/_base/helm/app/templates/pod-disruption-budgets.yaml
Labels: bug, harness-all

#658 Allow defining replicas from attributes for application deployments, …
  src/_base/helm/app/templates/application/console/deployment.yaml
  src/_base/helm/app/templates/application/cron/deployment.yaml
  src/_base/helm/app/templates/application/webapp/deployment.yaml
  src/akeneo/helm/app/templates/application/job-queue-consumer/deployment.yaml
  src/spryker/helm/app/templates/application/jenkins-runner/deployment.yaml
Labels: enhancement, harness-all

#660 Document that need to downgrade database.platform_version too
  UPGRADE.md
Labels: enhancement

#662 Switch kubeval's k8s spec location to fork
  src/_base/harness/attributes/common.yml
  src/_base/harness/config/pipeline.yml
Labels: enhancement, harness-all, migrate-to-harness-docker

#661 Update elasticsearch for another log4j CVE
  src/_base/harness/attributes/common.yml
  src/spryker/harness.yml
Labels: bug, harness-all
