Repository inviqa/harness-base-php, pull requests merged in 2023-08, with the labels that each got.

#783 Fix redis enabled check
  src/_base/harness/attributes/docker-base.yml
Labels: bug, harness-all, migrate-to-harness-docker

#784 Fix Upgrade.md change removing 1.5.x note header
  UPGRADE.md
Labels: bug

#785 Ensure all startup commands convert sidekick run to passthru
  src/_base/docker/image/console/root/entrypoint.sh.twig
  src/_base/docker/image/console/root/usr/lib/sidekick.sh
  src/_base/docker/image/cron/root/entrypoint.sh.twig
  src/_base/docker/image/php-fpm/root/entrypoint.sh.twig
Labels: enhancement, harness-all

#786 Ensure static builds convert sidekick run to passthru
  src/_base/docker/image/console/Dockerfile.twig
Labels: enhancement, harness-all

#787 Simplify release process using Github released archives
  .github/workflows/release-archives.yml
  build
Labels: enhancement

#780 Use the extended utilization metrics for HPA when v2 used in k8s 1.23+
  src/_base/helm/app/templates/horizontal-pod-autoscaler.yaml
Labels: enhancement

#788 Update github actions tag workflow to remove node12 warning
  .github/workflows/release-archives.yml
Labels: bug
