Repository inviqa/harness-base-php, pull requests merged in 2024-08, with the labels that each got.

#812 fix(magento2): switch tests to community edition
  Jenkinsfile
  src/magento2/.ci/sample-dynamic/workspace.yml
  src/magento2/.ci/sample-static/workspace.yml
Labels: bug, harness-magento2

#810 feat: switch to inviqa chromium image everywhere
  src/_base/_twig/docker-compose.yml/service/chrome.yml.twig
Labels: bug, harness-all

#817 chore(spryker): test only if harness-spryker label is on PR
  Jenkinsfile
Labels: enhancement, harness-spryker
